version: "3"
services:  
  web:
    build:
      context: ./client-reactjs
      dockerfile: Dockerfile
    networks:
      - tombolo-network
    environment:
      PORT: ${WEB_PORT}
      PROXY_URL: http://node:${PORT}
      WEB_EXPOSED_PORT: ${WEB_EXPOSED_PORT}
      WEB_EXPOSED_HTTP_PORT: ${WEB_EXPOSED_HTTP_PORT}
      HOSTNAME: ${HOST_HOSTNAME}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${WEB_EXPOSED_PORT}:${WEB_EXPOSED_PORT}
      - ${WEB_EXPOSED_HTTP_PORT}:${WEB_EXPOSED_HTTP_PORT}
    volumes:
      - ${CERT_PATH}:/etc/ssl
    depends_on:
      - mysql_db
    env_file:
      - .env
    entrypoint: [sh, /etc/nginx/run_nginx.sh, "${HOST_HOSTNAME}"]
  node:
    #restart: always
    entrypoint: [sh, ./docker-entry.sh, "mysql_db", "${DB_PORT}"]
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /tmp/pm2
    networks:
      - tombolo-network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql_db
    env_file:
      - .env  
networks:
  tombolo-network:
    driver: bridge
