name: Build  
on: 
  push:
      branches:
        - master
env:
  PORT: ${{ secrets.PORT }}
  WEB_PORT: ${{ secrets.WEB_PORT }}
  WEB_EXPOSED_PORT: ${{ secrets.WEB_EXPOSED_PORT }}
  WEB_EXPOSED_HTTP_PORT: ${{ secrets.WEB_EXPOSED_HTTP_PORT }}
  PROXY_URL: ${{ secrets.PROXY_URL }}
  HOST_HOSTNAME: ${{ secrets.HOST_HOSTNAME }}
  WEB_URL: ${{ secrets.WEB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
  AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
  AUTHSERVICE_TOMBOLO_CLIENT_ID: ${{ secrets.AUTHSERVICE_TOMBOLO_CLIENT_ID }}
  secret: ${{ secrets.secret }}
  REACT_APP_PROXY_URL: ${{ secrets.REACT_APP_PROXY_URL }}
  NODE_VERSION: '14.x'
  AZURE_WEBAPP_PACKAGE_PATH: 'build'
  
jobs:    
  build-ui:
    name: build-ui-container      
    runs-on: self-hosted    
    environment:
      name: 'DEV'
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      working-directory: 'client-reactjs'
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        CI=false npm run build --if-present        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'tomboloui-eastus2-dev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
