name: Build  
on: 
  push:
      branches:
        - master
jobs:
  build:
    runs-on: self-hosted
    steps:            
    - uses: actions/checkout@v2
    - run: |
        #build 
        docker build -t tombolo-ui ./client-reactjs
        #tag
        docker tag tombolo-ui tombolodevcr.azurecr.io/tombolo-ui
        #login to container registry
        az login --identity
        az group list
        az acr login --name tombolodevcr
        az acr repository list --name tombolodevcr.azurecr.io
        #push image to acr
        docker push tombolodevcr.azurecr.io/tombolo-ui
        #az acr repository list --name tombolodevcr --output table
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'tomboloui-eastus2-dev'
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'tombolodevcr.azurecr.io/tombolo-ui'
