name: Build  
on: 
  push:
      branches:
        - master
env:
  PORT: ${{ secrets.PORT }}
  WEB_PORT: ${{ secrets.WEB_PORT }}
  WEB_EXPOSED_PORT: ${{ secrets.WEB_EXPOSED_PORT }}
  WEB_EXPOSED_HTTP_PORT: ${{ secrets.WEB_EXPOSED_HTTP_PORT }}
  PROXY_URL: ${{ secrets.PROXY_URL }}
  HOST_HOSTNAME: ${{ secrets.HOST_HOSTNAME }}
  WEB_URL: ${{ secrets.WEB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
  AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
  AUTHSERVICE_TOMBOLO_CLIENT_ID: ${{ secrets.AUTHSERVICE_TOMBOLO_CLIENT_ID }}
  REACT_APP_PROXY_URL: ${{ secrets.REACT_APP_PROXY_URL }}
  secret: ${{ secrets.secret }}
  AZURE_WEBAPP_PACKAGE_PATH: './client-reactjs/build'
  AZURE_WEBAPP_PACKAGE_PATH_API: './server'
  JOB_COMPLETE_GROUP_ID: 'tombolo_dev'

jobs:    
  build-ui:
    name: build-ui-container      
    runs-on: self-hosted    
    environment:
      name: 'DEV'
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        CI=false && npm run build --if-present
        
        az login --identity
        
        zip -r tombolo-ui.zip .
        
        #az webapp deploy --resource-group app-tombolo-dev-eastus2 --name tomboloui2-eastus2-dev --src-path tombolo-ui.zip
        Publish-AzWebApp -ResourceGroupName app-tombolo-dev-eastus2 -Name tomboloui2-eastus2-dev -ArchivePath tombolo-ui.zip 
      working-directory: client-reactjs          
  
