name: Build  
on: 
  push:
      branches:
        - master
env:
  PORT: ${{ secrets.PORT }}
  WEB_PORT: ${{ secrets.WEB_PORT }}
  WEB_EXPOSED_PORT: ${{ secrets.WEB_EXPOSED_PORT }}
  WEB_EXPOSED_HTTP_PORT: ${{ secrets.WEB_EXPOSED_HTTP_PORT }}
  PROXY_URL: ${{ secrets.PROXY_URL }}
  HOST_HOSTNAME: ${{ secrets.HOST_HOSTNAME }}
  WEB_URL: ${{ secrets.WEB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
  AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
  AUTHSERVICE_TOMBOLO_CLIENT_ID: ${{ secrets.AUTHSERVICE_TOMBOLO_CLIENT_ID }}
  secret: ${{ secrets.secret }}        
  REACT_APP_PROXY_URL: ${{ secrets.REACT_APP_PROXY_URL }}
jobs:    
  build-ui:
    name: build-ui-container      
    runs-on: self-hosted    
    environment:
      name: 'DEV'
    steps:            
    - uses: actions/checkout@v2
    
    - name: create env file
      run: |
        touch .env
        echo REACT_APP_PROXY_URL=${{ secrets.REACT_APP_PROXY_URL }} >> .env
      working-directory: client-reactjs
      
    - run: |                        
        #build
        #docker rmi tombolo-ui:latest
        docker build -t tombolo-ui ./client-reactjs
        
        #tag
        docker tag tombolo-ui tombolodevcr.azurecr.io/tombolo-ui
        
        #login to Azure
        az login --identity
        
        #login to container registry
        az acr login --name tombolodevcr        
        
        #push image to acr
        docker push tombolodevcr.azurecr.io/tombolo-ui
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'tomboloui-eastus2-dev'
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'tombolodevcr.azurecr.io/tombolo-ui'
        
  build_api:
    name: build-api-container
    runs-on: self-hosted
    environment:
      name: 'DEV'
    steps:            
    - uses: actions/checkout@v2
    - name: create env file
      run: |
        touch .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_HOSTNAME=${{ secrets.DB_HOSTNAME }} >> .env
        echo AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }} >> .env
        echo AUTHSERVICE_TOMBOLO_CLIENT_ID=${{ secrets.AUTHSERVICE_TOMBOLO_CLIENT_ID }} >> .env
        echo secret=${{ secrets.secret }} >> .env
      working-directory: server
    
    - run: |                
        #build 
        docker build -t tombolo-api ./server        
        #tag
        docker tag tombolo-api tombolodevcr.azurecr.io/tombolo-api
        #login to Azure
        az login --identity        
        #login to container registry
        az acr login --name tombolodevcr        
        #push image to acr
        docker push tombolodevcr.azurecr.io/tombolo-api
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'tomboloapicontainer-eastus2-dev'
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'tombolodevcr.azurecr.io/tombolo-api'      
