name: Build  
on: 
  push:
      branches:
        - master
jobs:
  build-ui:
    name: build-ui-container      
    runs-on: self-hosted  
    steps:            
    - uses: actions/checkout@v2    
    - run: |                
        #build 
        docker build -t tombolo-ui ./client-reactjs
        
        #tag
        docker tag tombolo-ui tombolodevcr.azurecr.io/tombolo-ui
        
        #login to Azure
        az login --identity
        
        #login to container registry
        az acr login --name tombolodevcr        
        
        #push image to acr
        docker push tombolodevcr.azurecr.io/tombolo-ui
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'tomboloui-eastus2-dev'
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'tombolodevcr.azurecr.io/tombolo-ui'
